name: Codecov CI
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
            python-version: 3.7
      - name: Install python dependencies
        run: |
            python -m pip install --upgrade pip
            pip install NEMtropy  
      - name: Set up Julia 1.7
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.7"
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3