name: Codecov CI
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 2023rework
      - name: Set up Julia 1.9
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.9"
      - name: Cache artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.julia/artifacts
            ~/.julia/registries
            ~/.julia/packages
          key: ${{ runner.os }}-julia-${{ hashFiles('**/Project.toml') }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
